SNOWFLAKE_PROD_WAREHOUSE = "DAGSTER_WH"
SNOWFLAKE_DEV_WAREHOUSE = "DAGSTER_WH"
SNOWFLAKE_PROD_DATABASE = "DAGSTER_PROD_DB"
SNOWFLAKE_DEV_DATABASE = "DAGSTER_DEV_DB"
SNOWFLAKE_PROD_ROLE = "ROLE_DAGSTER_PROD"
SNOWFLAKE_DEV_ROLE = "ROLE_DAGSTER_DEV"

RAW_SCHEMA = "RAW"
PROCESSED_SCHEMA = "PROCESSED"